# Generated by Django 4.0 on 2021-12-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
